version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    mnd:
      ignored-files:
        - 'render.go'
        - 'navigation.go'
        - 'model.go'
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
    funlen:
      lines: 80
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - unnecessaryBlock
        - hugeParam
        - evalOrder
        - singleCaseSwitch
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G115 # Potential integer overflow when converting between integer types
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
    unused:
      # Mark all struct fields that have been written to as used.
      # Default: true
      field-writes-are-uses: true
      # Treat IncDec statement (e.g. `i++` or `i--`) as both read and write operation instead of just write.
      # Default: false
      post-statements-are-reads: true
      # Mark all exported fields as used.
      # default: true
      exported-fields-are-used: true
      # Mark all function parameters as used.
      # default: true
      parameters-are-used: true
      # Mark all local variables as used.
      # default: true
      local-variables-are-used: true
      # Mark all identifiers inside generated files as used.
      # Default: true
      generated-is-used: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
    paths:
      - bin/
      - downloads/

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - bin/
      - downloads/