// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: server.proto

//go:build protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for service health
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PingRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PingRequest_builder) Build() *PingRequest {
	m0 := &PingRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PingResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PingResponse_builder) Build() *PingResponse {
	m0 := &PingResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Messages for user registration
type RegisterUserRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterUserRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterUserRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterUserRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterUserRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterUserRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterUserRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *RegisterUserRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type RegisterUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 RegisterUserRequest_builder) Build() *RegisterUserRequest {
	m0 := &RegisterUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type RegisterUserResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          uint64                 `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Login       *string                `protobuf:"bytes,2,opt,name=login"`
	xxx_hidden_Token       *string                `protobuf:"bytes,3,opt,name=token"`
	xxx_hidden_Success     bool                   `protobuf:"varint,4,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterUserResponse) GetId() uint64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *RegisterUserResponse) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterUserResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *RegisterUserResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *RegisterUserResponse) SetId(v uint64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *RegisterUserResponse) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *RegisterUserResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *RegisterUserResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *RegisterUserResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterUserResponse) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterUserResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterUserResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *RegisterUserResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *RegisterUserResponse) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Login = nil
}

func (x *RegisterUserResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Token = nil
}

func (x *RegisterUserResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Success = false
}

type RegisterUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *uint64
	Login   *string
	Token   *string
	Success *bool
}

func (b0 RegisterUserResponse_builder) Build() *RegisterUserResponse {
	m0 := &RegisterUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Login = b.Login
	}
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Token = b.Token
	}
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

// Messages for user login
type LoginUserRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginUserRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginUserRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginUserRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginUserRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginUserRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginUserRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *LoginUserRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 LoginUserRequest_builder) Build() *LoginUserRequest {
	m0 := &LoginUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginUserResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_Success     bool                   `protobuf:"varint,2,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginUserResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *LoginUserResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *LoginUserResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginUserResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginUserResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginUserResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginUserResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *LoginUserResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Success = false
}

type LoginUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token   *string
	Success *bool
}

func (b0 LoginUserResponse_builder) Build() *LoginUserResponse {
	m0 := &LoginUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

// Messages for changing password
type ChangePasswordRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CurrentPassword *string                `protobuf:"bytes,1,opt,name=current_password,json=currentPassword"`
	xxx_hidden_NewPassword     *string                `protobuf:"bytes,2,opt,name=new_password,json=newPassword"`
	xxx_hidden_Login           *string                `protobuf:"bytes,3,opt,name=login"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		if x.xxx_hidden_CurrentPassword != nil {
			return *x.xxx_hidden_CurrentPassword
		}
		return ""
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		if x.xxx_hidden_NewPassword != nil {
			return *x.xxx_hidden_NewPassword
		}
		return ""
	}
	return ""
}

func (x *ChangePasswordRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *ChangePasswordRequest) SetCurrentPassword(v string) {
	x.xxx_hidden_CurrentPassword = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ChangePasswordRequest) SetNewPassword(v string) {
	x.xxx_hidden_NewPassword = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ChangePasswordRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ChangePasswordRequest) HasCurrentPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChangePasswordRequest) HasNewPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ChangePasswordRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ChangePasswordRequest) ClearCurrentPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CurrentPassword = nil
}

func (x *ChangePasswordRequest) ClearNewPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NewPassword = nil
}

func (x *ChangePasswordRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Login = nil
}

type ChangePasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CurrentPassword *string
	NewPassword     *string
	Login           *string
}

func (b0 ChangePasswordRequest_builder) Build() *ChangePasswordRequest {
	m0 := &ChangePasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CurrentPassword != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_CurrentPassword = b.CurrentPassword
	}
	if b.NewPassword != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_NewPassword = b.NewPassword
	}
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Login = b.Login
	}
	return m0
}

type ChangePasswordResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *ChangePasswordResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ChangePasswordResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChangePasswordResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type ChangePasswordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 ChangePasswordResponse_builder) Build() *ChangePasswordResponse {
	m0 := &ChangePasswordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

// Message for saving new vault data
type SaveVaultRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_DataType     *string                `protobuf:"bytes,2,opt,name=data_type,json=dataType"`
	xxx_hidden_EcryptedData []byte                 `protobuf:"bytes,3,opt,name=ecrypted_data,json=ecryptedData"`
	xxx_hidden_MetaData     *structpb.Struct       `protobuf:"bytes,4,opt,name=meta_data,json=metaData"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SaveVaultRequest) Reset() {
	*x = SaveVaultRequest{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVaultRequest) ProtoMessage() {}

func (x *SaveVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveVaultRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SaveVaultRequest) GetDataType() string {
	if x != nil {
		if x.xxx_hidden_DataType != nil {
			return *x.xxx_hidden_DataType
		}
		return ""
	}
	return ""
}

func (x *SaveVaultRequest) GetEcryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EcryptedData
	}
	return nil
}

func (x *SaveVaultRequest) GetMetaData() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_MetaData
	}
	return nil
}

func (x *SaveVaultRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *SaveVaultRequest) SetDataType(v string) {
	x.xxx_hidden_DataType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *SaveVaultRequest) SetEcryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EcryptedData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *SaveVaultRequest) SetMetaData(v *structpb.Struct) {
	x.xxx_hidden_MetaData = v
}

func (x *SaveVaultRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SaveVaultRequest) HasDataType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SaveVaultRequest) HasEcryptedData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SaveVaultRequest) HasMetaData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MetaData != nil
}

func (x *SaveVaultRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *SaveVaultRequest) ClearDataType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_DataType = nil
}

func (x *SaveVaultRequest) ClearEcryptedData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EcryptedData = nil
}

func (x *SaveVaultRequest) ClearMetaData() {
	x.xxx_hidden_MetaData = nil
}

type SaveVaultRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name         *string
	DataType     *string
	EcryptedData []byte
	MetaData     *structpb.Struct
}

func (b0 SaveVaultRequest_builder) Build() *SaveVaultRequest {
	m0 := &SaveVaultRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.DataType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_DataType = b.DataType
	}
	if b.EcryptedData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_EcryptedData = b.EcryptedData
	}
	x.xxx_hidden_MetaData = b.MetaData
	return m0
}

type SaveVaultResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SaveVaultResponse) Reset() {
	*x = SaveVaultResponse{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVaultResponse) ProtoMessage() {}

func (x *SaveVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *SaveVaultResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SaveVaultResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SaveVaultResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type SaveVaultResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 SaveVaultResponse_builder) Build() *SaveVaultResponse {
	m0 := &SaveVaultResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

// Message for soft deletion of user's vault record
type DeactivateVaultRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SecretId    int32                  `protobuf:"varint,1,opt,name=secret_id,json=secretId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeactivateVaultRequest) Reset() {
	*x = DeactivateVaultRequest{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateVaultRequest) ProtoMessage() {}

func (x *DeactivateVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeactivateVaultRequest) GetSecretId() int32 {
	if x != nil {
		return x.xxx_hidden_SecretId
	}
	return 0
}

func (x *DeactivateVaultRequest) SetSecretId(v int32) {
	x.xxx_hidden_SecretId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeactivateVaultRequest) HasSecretId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeactivateVaultRequest) ClearSecretId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SecretId = 0
}

type DeactivateVaultRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SecretId *int32
}

func (b0 DeactivateVaultRequest_builder) Build() *DeactivateVaultRequest {
	m0 := &DeactivateVaultRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SecretId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SecretId = *b.SecretId
	}
	return m0
}

type DeactivateVaultResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeactivateVaultResponse) Reset() {
	*x = DeactivateVaultResponse{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateVaultResponse) ProtoMessage() {}

func (x *DeactivateVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeactivateVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *DeactivateVaultResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeactivateVaultResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeactivateVaultResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

type DeactivateVaultResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
}

func (b0 DeactivateVaultResponse_builder) Build() *DeactivateVaultResponse {
	m0 := &DeactivateVaultResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

// Messages for fetching user's vaults using streams
type VaultItem struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId"`
	xxx_hidden_Name          *string                `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_DataType      *string                `protobuf:"bytes,4,opt,name=data_type,json=dataType"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,5,opt,name=encrypted_data,json=encryptedData"`
	xxx_hidden_MetaData      *structpb.Struct       `protobuf:"bytes,6,opt,name=meta_data,json=metaData"`
	xxx_hidden_CreatedAt     *string                `protobuf:"bytes,7,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt     *string                `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_Active        bool                   `protobuf:"varint,9,opt,name=active"`
	xxx_hidden_Version       int32                  `protobuf:"varint,10,opt,name=version"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VaultItem) Reset() {
	*x = VaultItem{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItem) ProtoMessage() {}

func (x *VaultItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VaultItem) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *VaultItem) GetUserId() int32 {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return 0
}

func (x *VaultItem) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetDataType() string {
	if x != nil {
		if x.xxx_hidden_DataType != nil {
			return *x.xxx_hidden_DataType
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *VaultItem) GetMetaData() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_MetaData
	}
	return nil
}

func (x *VaultItem) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *VaultItem) GetActive() bool {
	if x != nil {
		return x.xxx_hidden_Active
	}
	return false
}

func (x *VaultItem) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *VaultItem) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *VaultItem) SetUserId(v int32) {
	x.xxx_hidden_UserId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *VaultItem) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *VaultItem) SetDataType(v string) {
	x.xxx_hidden_DataType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *VaultItem) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *VaultItem) SetMetaData(v *structpb.Struct) {
	x.xxx_hidden_MetaData = v
}

func (x *VaultItem) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *VaultItem) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *VaultItem) SetActive(v bool) {
	x.xxx_hidden_Active = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *VaultItem) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *VaultItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *VaultItem) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VaultItem) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VaultItem) HasDataType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VaultItem) HasEncryptedData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *VaultItem) HasMetaData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MetaData != nil
}

func (x *VaultItem) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *VaultItem) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *VaultItem) HasActive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *VaultItem) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *VaultItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *VaultItem) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserId = 0
}

func (x *VaultItem) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *VaultItem) ClearDataType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_DataType = nil
}

func (x *VaultItem) ClearEncryptedData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EncryptedData = nil
}

func (x *VaultItem) ClearMetaData() {
	x.xxx_hidden_MetaData = nil
}

func (x *VaultItem) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_CreatedAt = nil
}

func (x *VaultItem) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_UpdatedAt = nil
}

func (x *VaultItem) ClearActive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Active = false
}

func (x *VaultItem) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Version = 0
}

type VaultItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *int32
	UserId        *int32
	Name          *string
	DataType      *string
	EncryptedData []byte
	MetaData      *structpb.Struct
	CreatedAt     *string
	UpdatedAt     *string
	Active        *bool
	Version       *int32
}

func (b0 VaultItem_builder) Build() *VaultItem {
	m0 := &VaultItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = *b.Id
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_UserId = *b.UserId
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Name = b.Name
	}
	if b.DataType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_DataType = b.DataType
	}
	if b.EncryptedData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_EncryptedData = b.EncryptedData
	}
	x.xxx_hidden_MetaData = b.MetaData
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	if b.Active != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_Active = *b.Active
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type VaultItemChunk struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Item               *VaultItem             `protobuf:"bytes,1,opt,name=item"`
	xxx_hidden_EncryptedDataChunk []byte                 `protobuf:"bytes,2,opt,name=encrypted_data_chunk,json=encryptedDataChunk"`
	xxx_hidden_ChunkIndex         int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex"`
	xxx_hidden_TotalChunks        int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks"`
	xxx_hidden_IsFirstChunk       bool                   `protobuf:"varint,5,opt,name=is_first_chunk,json=isFirstChunk"`
	xxx_hidden_IsLastChunk        bool                   `protobuf:"varint,6,opt,name=is_last_chunk,json=isLastChunk"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *VaultItemChunk) Reset() {
	*x = VaultItemChunk{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItemChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItemChunk) ProtoMessage() {}

func (x *VaultItemChunk) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VaultItemChunk) GetItem() *VaultItem {
	if x != nil {
		return x.xxx_hidden_Item
	}
	return nil
}

func (x *VaultItemChunk) GetEncryptedDataChunk() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDataChunk
	}
	return nil
}

func (x *VaultItemChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.xxx_hidden_ChunkIndex
	}
	return 0
}

func (x *VaultItemChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.xxx_hidden_TotalChunks
	}
	return 0
}

func (x *VaultItemChunk) GetIsFirstChunk() bool {
	if x != nil {
		return x.xxx_hidden_IsFirstChunk
	}
	return false
}

func (x *VaultItemChunk) GetIsLastChunk() bool {
	if x != nil {
		return x.xxx_hidden_IsLastChunk
	}
	return false
}

func (x *VaultItemChunk) SetItem(v *VaultItem) {
	x.xxx_hidden_Item = v
}

func (x *VaultItemChunk) SetEncryptedDataChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDataChunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *VaultItemChunk) SetChunkIndex(v int32) {
	x.xxx_hidden_ChunkIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *VaultItemChunk) SetTotalChunks(v int32) {
	x.xxx_hidden_TotalChunks = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *VaultItemChunk) SetIsFirstChunk(v bool) {
	x.xxx_hidden_IsFirstChunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *VaultItemChunk) SetIsLastChunk(v bool) {
	x.xxx_hidden_IsLastChunk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *VaultItemChunk) HasItem() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Item != nil
}

func (x *VaultItemChunk) HasEncryptedDataChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *VaultItemChunk) HasChunkIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *VaultItemChunk) HasTotalChunks() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *VaultItemChunk) HasIsFirstChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *VaultItemChunk) HasIsLastChunk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *VaultItemChunk) ClearItem() {
	x.xxx_hidden_Item = nil
}

func (x *VaultItemChunk) ClearEncryptedDataChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedDataChunk = nil
}

func (x *VaultItemChunk) ClearChunkIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ChunkIndex = 0
}

func (x *VaultItemChunk) ClearTotalChunks() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_TotalChunks = 0
}

func (x *VaultItemChunk) ClearIsFirstChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_IsFirstChunk = false
}

func (x *VaultItemChunk) ClearIsLastChunk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_IsLastChunk = false
}

type VaultItemChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Item               *VaultItem
	EncryptedDataChunk []byte
	ChunkIndex         *int32
	TotalChunks        *int32
	IsFirstChunk       *bool
	IsLastChunk        *bool
}

func (b0 VaultItemChunk_builder) Build() *VaultItemChunk {
	m0 := &VaultItemChunk{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Item = b.Item
	if b.EncryptedDataChunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_EncryptedDataChunk = b.EncryptedDataChunk
	}
	if b.ChunkIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_ChunkIndex = *b.ChunkIndex
	}
	if b.TotalChunks != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_TotalChunks = *b.TotalChunks
	}
	if b.IsFirstChunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_IsFirstChunk = *b.IsFirstChunk
	}
	if b.IsLastChunk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_IsLastChunk = *b.IsLastChunk
	}
	return m0
}

type StreamMetadata struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TotalItems       int32                  `protobuf:"varint,1,opt,name=total_items,json=totalItems"`
	xxx_hidden_CurrentItemIndex int32                  `protobuf:"varint,2,opt,name=current_item_index,json=currentItemIndex"`
	xxx_hidden_IsFirstItem      bool                   `protobuf:"varint,3,opt,name=is_first_item,json=isFirstItem"`
	xxx_hidden_IsLastItem       bool                   `protobuf:"varint,4,opt,name=is_last_item,json=isLastItem"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamMetadata) GetTotalItems() int32 {
	if x != nil {
		return x.xxx_hidden_TotalItems
	}
	return 0
}

func (x *StreamMetadata) GetCurrentItemIndex() int32 {
	if x != nil {
		return x.xxx_hidden_CurrentItemIndex
	}
	return 0
}

func (x *StreamMetadata) GetIsFirstItem() bool {
	if x != nil {
		return x.xxx_hidden_IsFirstItem
	}
	return false
}

func (x *StreamMetadata) GetIsLastItem() bool {
	if x != nil {
		return x.xxx_hidden_IsLastItem
	}
	return false
}

func (x *StreamMetadata) SetTotalItems(v int32) {
	x.xxx_hidden_TotalItems = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *StreamMetadata) SetCurrentItemIndex(v int32) {
	x.xxx_hidden_CurrentItemIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *StreamMetadata) SetIsFirstItem(v bool) {
	x.xxx_hidden_IsFirstItem = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *StreamMetadata) SetIsLastItem(v bool) {
	x.xxx_hidden_IsLastItem = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *StreamMetadata) HasTotalItems() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StreamMetadata) HasCurrentItemIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StreamMetadata) HasIsFirstItem() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StreamMetadata) HasIsLastItem() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StreamMetadata) ClearTotalItems() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TotalItems = 0
}

func (x *StreamMetadata) ClearCurrentItemIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CurrentItemIndex = 0
}

func (x *StreamMetadata) ClearIsFirstItem() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IsFirstItem = false
}

func (x *StreamMetadata) ClearIsLastItem() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_IsLastItem = false
}

type StreamMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TotalItems       *int32
	CurrentItemIndex *int32
	IsFirstItem      *bool
	IsLastItem       *bool
}

func (b0 StreamMetadata_builder) Build() *StreamMetadata {
	m0 := &StreamMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TotalItems != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_TotalItems = *b.TotalItems
	}
	if b.CurrentItemIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_CurrentItemIndex = *b.CurrentItemIndex
	}
	if b.IsFirstItem != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_IsFirstItem = *b.IsFirstItem
	}
	if b.IsLastItem != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_IsLastItem = *b.IsLastItem
	}
	return m0
}

type StreamVaultsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVaultsRequest) Reset() {
	*x = StreamVaultsRequest{}
	mi := &file_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVaultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVaultsRequest) ProtoMessage() {}

func (x *StreamVaultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type StreamVaultsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 StreamVaultsRequest_builder) Build() *StreamVaultsRequest {
	m0 := &StreamVaultsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type StreamVaultsResponse struct {
	state              protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Payload isStreamVaultsResponse_Payload `protobuf_oneof:"payload"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StreamVaultsResponse) Reset() {
	*x = StreamVaultsResponse{}
	mi := &file_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVaultsResponse) ProtoMessage() {}

func (x *StreamVaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StreamVaultsResponse) GetItemChunk() *VaultItemChunk {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*streamVaultsResponse_ItemChunk); ok {
			return x.ItemChunk
		}
	}
	return nil
}

func (x *StreamVaultsResponse) GetMetadata() *StreamMetadata {
	if x != nil {
		if x, ok := x.xxx_hidden_Payload.(*streamVaultsResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StreamVaultsResponse) SetItemChunk(v *VaultItemChunk) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &streamVaultsResponse_ItemChunk{v}
}

func (x *StreamVaultsResponse) SetMetadata(v *StreamMetadata) {
	if v == nil {
		x.xxx_hidden_Payload = nil
		return
	}
	x.xxx_hidden_Payload = &streamVaultsResponse_Metadata{v}
}

func (x *StreamVaultsResponse) HasPayload() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Payload != nil
}

func (x *StreamVaultsResponse) HasItemChunk() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*streamVaultsResponse_ItemChunk)
	return ok
}

func (x *StreamVaultsResponse) HasMetadata() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Payload.(*streamVaultsResponse_Metadata)
	return ok
}

func (x *StreamVaultsResponse) ClearPayload() {
	x.xxx_hidden_Payload = nil
}

func (x *StreamVaultsResponse) ClearItemChunk() {
	if _, ok := x.xxx_hidden_Payload.(*streamVaultsResponse_ItemChunk); ok {
		x.xxx_hidden_Payload = nil
	}
}

func (x *StreamVaultsResponse) ClearMetadata() {
	if _, ok := x.xxx_hidden_Payload.(*streamVaultsResponse_Metadata); ok {
		x.xxx_hidden_Payload = nil
	}
}

const StreamVaultsResponse_Payload_not_set_case case_StreamVaultsResponse_Payload = 0
const StreamVaultsResponse_ItemChunk_case case_StreamVaultsResponse_Payload = 1
const StreamVaultsResponse_Metadata_case case_StreamVaultsResponse_Payload = 2

func (x *StreamVaultsResponse) WhichPayload() case_StreamVaultsResponse_Payload {
	if x == nil {
		return StreamVaultsResponse_Payload_not_set_case
	}
	switch x.xxx_hidden_Payload.(type) {
	case *streamVaultsResponse_ItemChunk:
		return StreamVaultsResponse_ItemChunk_case
	case *streamVaultsResponse_Metadata:
		return StreamVaultsResponse_Metadata_case
	default:
		return StreamVaultsResponse_Payload_not_set_case
	}
}

type StreamVaultsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Payload:
	ItemChunk *VaultItemChunk
	Metadata  *StreamMetadata
	// -- end of xxx_hidden_Payload
}

func (b0 StreamVaultsResponse_builder) Build() *StreamVaultsResponse {
	m0 := &StreamVaultsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ItemChunk != nil {
		x.xxx_hidden_Payload = &streamVaultsResponse_ItemChunk{b.ItemChunk}
	}
	if b.Metadata != nil {
		x.xxx_hidden_Payload = &streamVaultsResponse_Metadata{b.Metadata}
	}
	return m0
}

type case_StreamVaultsResponse_Payload protoreflect.FieldNumber

func (x case_StreamVaultsResponse_Payload) String() string {
	md := file_server_proto_msgTypes[16].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isStreamVaultsResponse_Payload interface {
	isStreamVaultsResponse_Payload()
}

type streamVaultsResponse_ItemChunk struct {
	ItemChunk *VaultItemChunk `protobuf:"bytes,1,opt,name=item_chunk,json=itemChunk,oneof"`
}

type streamVaultsResponse_Metadata struct {
	Metadata *StreamMetadata `protobuf:"bytes,2,opt,name=metadata,oneof"`
}

func (*streamVaultsResponse_ItemChunk) isStreamVaultsResponse_Payload() {}

func (*streamVaultsResponse_Metadata) isStreamVaultsResponse_Payload() {}

// Messages for uploading file data into the vault using chunks
type UploadFileRequest struct {
	state                  protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_FileName    *string                  `protobuf:"bytes,1,opt,name=file_name,json=fileName"`
	xxx_hidden_Data        isUploadFileRequest_Data `protobuf_oneof:"data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		if x.xxx_hidden_FileName != nil {
			return *x.xxx_hidden_FileName
		}
		return ""
	}
	return ""
}

func (x *UploadFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*uploadFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

func (x *UploadFileRequest) GetMetaData() *structpb.Struct {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*uploadFileRequest_MetaData); ok {
			return x.MetaData
		}
	}
	return nil
}

func (x *UploadFileRequest) SetFileName(v string) {
	x.xxx_hidden_FileName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UploadFileRequest) SetChunkData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = &uploadFileRequest_ChunkData{v}
}

func (x *UploadFileRequest) SetMetaData(v *structpb.Struct) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &uploadFileRequest_MetaData{v}
}

func (x *UploadFileRequest) HasFileName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UploadFileRequest) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *UploadFileRequest) HasChunkData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*uploadFileRequest_ChunkData)
	return ok
}

func (x *UploadFileRequest) HasMetaData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*uploadFileRequest_MetaData)
	return ok
}

func (x *UploadFileRequest) ClearFileName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FileName = nil
}

func (x *UploadFileRequest) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *UploadFileRequest) ClearChunkData() {
	if _, ok := x.xxx_hidden_Data.(*uploadFileRequest_ChunkData); ok {
		x.xxx_hidden_Data = nil
	}
}

func (x *UploadFileRequest) ClearMetaData() {
	if _, ok := x.xxx_hidden_Data.(*uploadFileRequest_MetaData); ok {
		x.xxx_hidden_Data = nil
	}
}

const UploadFileRequest_Data_not_set_case case_UploadFileRequest_Data = 0
const UploadFileRequest_ChunkData_case case_UploadFileRequest_Data = 2
const UploadFileRequest_MetaData_case case_UploadFileRequest_Data = 3

func (x *UploadFileRequest) WhichData() case_UploadFileRequest_Data {
	if x == nil {
		return UploadFileRequest_Data_not_set_case
	}
	switch x.xxx_hidden_Data.(type) {
	case *uploadFileRequest_ChunkData:
		return UploadFileRequest_ChunkData_case
	case *uploadFileRequest_MetaData:
		return UploadFileRequest_MetaData_case
	default:
		return UploadFileRequest_Data_not_set_case
	}
}

type UploadFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileName *string
	// Fields of oneof xxx_hidden_Data:
	ChunkData []byte
	MetaData  *structpb.Struct
	// -- end of xxx_hidden_Data
}

func (b0 UploadFileRequest_builder) Build() *UploadFileRequest {
	m0 := &UploadFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FileName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_FileName = b.FileName
	}
	if b.ChunkData != nil {
		x.xxx_hidden_Data = &uploadFileRequest_ChunkData{b.ChunkData}
	}
	if b.MetaData != nil {
		x.xxx_hidden_Data = &uploadFileRequest_MetaData{b.MetaData}
	}
	return m0
}

type case_UploadFileRequest_Data protoreflect.FieldNumber

func (x case_UploadFileRequest_Data) String() string {
	md := file_server_proto_msgTypes[17].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type uploadFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,oneof"`
}

type uploadFileRequest_MetaData struct {
	MetaData *structpb.Struct `protobuf:"bytes,3,opt,name=meta_data,json=metaData,oneof"`
}

func (*uploadFileRequest_ChunkData) isUploadFileRequest_Data() {}

func (*uploadFileRequest_MetaData) isUploadFileRequest_Data() {}

// Message for updating vault record
type UpdateVaultRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Name          *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData"`
	xxx_hidden_MetaData      *structpb.Struct       `protobuf:"bytes,4,opt,name=meta_data,json=metaData"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateVaultRequest) Reset() {
	*x = UpdateVaultRequest{}
	mi := &file_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultRequest) ProtoMessage() {}

func (x *UpdateVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateVaultRequest) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *UpdateVaultRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UpdateVaultRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedData
	}
	return nil
}

func (x *UpdateVaultRequest) GetMetaData() *structpb.Struct {
	if x != nil {
		return x.xxx_hidden_MetaData
	}
	return nil
}

func (x *UpdateVaultRequest) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *UpdateVaultRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *UpdateVaultRequest) SetEncryptedData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *UpdateVaultRequest) SetMetaData(v *structpb.Struct) {
	x.xxx_hidden_MetaData = v
}

func (x *UpdateVaultRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateVaultRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateVaultRequest) HasEncryptedData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UpdateVaultRequest) HasMetaData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MetaData != nil
}

func (x *UpdateVaultRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *UpdateVaultRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *UpdateVaultRequest) ClearEncryptedData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedData = nil
}

func (x *UpdateVaultRequest) ClearMetaData() {
	x.xxx_hidden_MetaData = nil
}

type UpdateVaultRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            *int32
	Name          *string
	EncryptedData []byte
	MetaData      *structpb.Struct
}

func (b0 UpdateVaultRequest_builder) Build() *UpdateVaultRequest {
	m0 := &UpdateVaultRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Name = b.Name
	}
	if b.EncryptedData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_EncryptedData = b.EncryptedData
	}
	x.xxx_hidden_MetaData = b.MetaData
	return m0
}

type UpdateVaultResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateVaultResponse) Reset() {
	*x = UpdateVaultResponse{}
	mi := &file_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVaultResponse) ProtoMessage() {}

func (x *UpdateVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *UpdateVaultResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *UpdateVaultResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateVaultResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UpdateVaultResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateVaultResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateVaultResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *UpdateVaultResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type UpdateVaultResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Success *bool
	Message *string
}

func (b0 UpdateVaultResponse_builder) Build() *UpdateVaultResponse {
	m0 := &UpdateVaultResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Success = *b.Success
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\x1a\x1cgoogle/protobuf/struct.proto\x1a!google/protobuf/go_features.proto\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"G\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"l\n" +
	"\x14RegisterUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x11LoginUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"{\n" +
	"\x15ChangePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\x10SaveVaultRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12#\n" +
	"\recrypted_data\x18\x03 \x01(\fR\fecryptedData\x124\n" +
	"\tmeta_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetaData\"-\n" +
	"\x11SaveVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x16DeactivateVaultRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\x05R\bsecretId\"3\n" +
	"\x17DeactivateVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x02\n" +
	"\tVaultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12%\n" +
	"\x0eencrypted_data\x18\x05 \x01(\fR\rencryptedData\x124\n" +
	"\tmeta_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetaData\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\"\xf7\x01\n" +
	"\x0eVaultItemChunk\x12%\n" +
	"\x04item\x18\x01 \x01(\v2\x11.server.VaultItemR\x04item\x120\n" +
	"\x14encrypted_data_chunk\x18\x02 \x01(\fR\x12encryptedDataChunk\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12$\n" +
	"\x0eis_first_chunk\x18\x05 \x01(\bR\fisFirstChunk\x12\"\n" +
	"\ris_last_chunk\x18\x06 \x01(\bR\visLastChunk\"\xa5\x01\n" +
	"\x0eStreamMetadata\x12\x1f\n" +
	"\vtotal_items\x18\x01 \x01(\x05R\n" +
	"totalItems\x12,\n" +
	"\x12current_item_index\x18\x02 \x01(\x05R\x10currentItemIndex\x12\"\n" +
	"\ris_first_item\x18\x03 \x01(\bR\visFirstItem\x12 \n" +
	"\fis_last_item\x18\x04 \x01(\bR\n" +
	"isLastItem\"\x15\n" +
	"\x13StreamVaultsRequest\"\x90\x01\n" +
	"\x14StreamVaultsResponse\x127\n" +
	"\n" +
	"item_chunk\x18\x01 \x01(\v2\x16.server.VaultItemChunkH\x00R\titemChunk\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.server.StreamMetadataH\x00R\bmetadataB\t\n" +
	"\apayload\"\x91\x01\n" +
	"\x11UploadFileRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkData\x126\n" +
	"\tmeta_data\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\bmetaDataB\x06\n" +
	"\x04data\"\x95\x01\n" +
	"\x12UpdateVaultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x124\n" +
	"\tmeta_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetaData\"I\n" +
	"\x13UpdateVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8a\x05\n" +
	"\n" +
	"GophKeeper\x121\n" +
	"\x04Ping\x12\x13.server.PingRequest\x1a\x14.server.PingResponse\x12I\n" +
	"\fRegisterUser\x12\x1b.server.RegisterUserRequest\x1a\x1c.server.RegisterUserResponse\x12@\n" +
	"\tLoginUser\x12\x18.server.LoginUserRequest\x1a\x19.server.LoginUserResponse\x12O\n" +
	"\x0eChangePassword\x12\x1d.server.ChangePasswordRequest\x1a\x1e.server.ChangePasswordResponse\x12@\n" +
	"\tSaveVault\x12\x18.server.SaveVaultRequest\x1a\x19.server.SaveVaultResponse\x12R\n" +
	"\x0fDeactivateVault\x12\x1e.server.DeactivateVaultRequest\x1a\x1f.server.DeactivateVaultResponse\x12<\n" +
	"\n" +
	"UploadFile\x12\x19.server.UploadFileRequest\x1a\x11.server.VaultItem(\x01\x12O\n" +
	"\x10GetSteamedVaults\x12\x1b.server.StreamVaultsRequest\x1a\x1c.server.StreamVaultsResponse0\x01\x12F\n" +
	"\vUpdateVault\x12\x1a.server.UpdateVaultRequest\x1a\x1b.server.UpdateVaultResponseB\x1fZ\x15internal/server/proto\x92\x03\x05\xd2>\x02\x10\x02b\beditionsp\xe8\a"

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_server_proto_goTypes = []any{
	(*PingRequest)(nil),             // 0: server.PingRequest
	(*PingResponse)(nil),            // 1: server.PingResponse
	(*RegisterUserRequest)(nil),     // 2: server.RegisterUserRequest
	(*RegisterUserResponse)(nil),    // 3: server.RegisterUserResponse
	(*LoginUserRequest)(nil),        // 4: server.LoginUserRequest
	(*LoginUserResponse)(nil),       // 5: server.LoginUserResponse
	(*ChangePasswordRequest)(nil),   // 6: server.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),  // 7: server.ChangePasswordResponse
	(*SaveVaultRequest)(nil),        // 8: server.SaveVaultRequest
	(*SaveVaultResponse)(nil),       // 9: server.SaveVaultResponse
	(*DeactivateVaultRequest)(nil),  // 10: server.DeactivateVaultRequest
	(*DeactivateVaultResponse)(nil), // 11: server.DeactivateVaultResponse
	(*VaultItem)(nil),               // 12: server.VaultItem
	(*VaultItemChunk)(nil),          // 13: server.VaultItemChunk
	(*StreamMetadata)(nil),          // 14: server.StreamMetadata
	(*StreamVaultsRequest)(nil),     // 15: server.StreamVaultsRequest
	(*StreamVaultsResponse)(nil),    // 16: server.StreamVaultsResponse
	(*UploadFileRequest)(nil),       // 17: server.UploadFileRequest
	(*UpdateVaultRequest)(nil),      // 18: server.UpdateVaultRequest
	(*UpdateVaultResponse)(nil),     // 19: server.UpdateVaultResponse
	(*structpb.Struct)(nil),         // 20: google.protobuf.Struct
}
var file_server_proto_depIdxs = []int32{
	20, // 0: server.SaveVaultRequest.meta_data:type_name -> google.protobuf.Struct
	20, // 1: server.VaultItem.meta_data:type_name -> google.protobuf.Struct
	12, // 2: server.VaultItemChunk.item:type_name -> server.VaultItem
	13, // 3: server.StreamVaultsResponse.item_chunk:type_name -> server.VaultItemChunk
	14, // 4: server.StreamVaultsResponse.metadata:type_name -> server.StreamMetadata
	20, // 5: server.UploadFileRequest.meta_data:type_name -> google.protobuf.Struct
	20, // 6: server.UpdateVaultRequest.meta_data:type_name -> google.protobuf.Struct
	0,  // 7: server.GophKeeper.Ping:input_type -> server.PingRequest
	2,  // 8: server.GophKeeper.RegisterUser:input_type -> server.RegisterUserRequest
	4,  // 9: server.GophKeeper.LoginUser:input_type -> server.LoginUserRequest
	6,  // 10: server.GophKeeper.ChangePassword:input_type -> server.ChangePasswordRequest
	8,  // 11: server.GophKeeper.SaveVault:input_type -> server.SaveVaultRequest
	10, // 12: server.GophKeeper.DeactivateVault:input_type -> server.DeactivateVaultRequest
	17, // 13: server.GophKeeper.UploadFile:input_type -> server.UploadFileRequest
	15, // 14: server.GophKeeper.GetSteamedVaults:input_type -> server.StreamVaultsRequest
	18, // 15: server.GophKeeper.UpdateVault:input_type -> server.UpdateVaultRequest
	1,  // 16: server.GophKeeper.Ping:output_type -> server.PingResponse
	3,  // 17: server.GophKeeper.RegisterUser:output_type -> server.RegisterUserResponse
	5,  // 18: server.GophKeeper.LoginUser:output_type -> server.LoginUserResponse
	7,  // 19: server.GophKeeper.ChangePassword:output_type -> server.ChangePasswordResponse
	9,  // 20: server.GophKeeper.SaveVault:output_type -> server.SaveVaultResponse
	11, // 21: server.GophKeeper.DeactivateVault:output_type -> server.DeactivateVaultResponse
	12, // 22: server.GophKeeper.UploadFile:output_type -> server.VaultItem
	16, // 23: server.GophKeeper.GetSteamedVaults:output_type -> server.StreamVaultsResponse
	19, // 24: server.GophKeeper.UpdateVault:output_type -> server.UpdateVaultResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_server_proto_msgTypes[16].OneofWrappers = []any{
		(*streamVaultsResponse_ItemChunk)(nil),
		(*streamVaultsResponse_Metadata)(nil),
	}
	file_server_proto_msgTypes[17].OneofWrappers = []any{
		(*uploadFileRequest_ChunkData)(nil),
		(*uploadFileRequest_MetaData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
