// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents request to register new user
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Message represents response to register new user
type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Message represents request to login user
type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Message represents response to login user
type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Message represents request to save data to vault
type SaveVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	EcryptedData  []byte                 `protobuf:"bytes,3,opt,name=ecrypted_data,json=ecryptedData,proto3" json:"ecrypted_data,omitempty"`
	MetaData      *structpb.Struct       `protobuf:"bytes,4,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVaultRequest) Reset() {
	*x = SaveVaultRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVaultRequest) ProtoMessage() {}

func (x *SaveVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVaultRequest.ProtoReflect.Descriptor instead.
func (*SaveVaultRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *SaveVaultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveVaultRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SaveVaultRequest) GetEcryptedData() []byte {
	if x != nil {
		return x.EcryptedData
	}
	return nil
}

func (x *SaveVaultRequest) GetMetaData() *structpb.Struct {
	if x != nil {
		return x.MetaData
	}
	return nil
}

// Message represents response to to save data to vault
type SaveVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveVaultResponse) Reset() {
	*x = SaveVaultResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveVaultResponse) ProtoMessage() {}

func (x *SaveVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveVaultResponse.ProtoReflect.Descriptor instead.
func (*SaveVaultResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *SaveVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VaultItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,5,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	MetaData      *structpb.Struct       `protobuf:"bytes,6,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Active        bool                   `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	Version       int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultItem) Reset() {
	*x = VaultItem{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItem) ProtoMessage() {}

func (x *VaultItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultItem.ProtoReflect.Descriptor instead.
func (*VaultItem) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *VaultItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VaultItem) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VaultItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultItem) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *VaultItem) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *VaultItem) GetMetaData() *structpb.Struct {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *VaultItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VaultItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *VaultItem) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *VaultItem) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Message represents response to retrieve all vaults saved by user
type GetUserVaultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vaults        []*VaultItem           `protobuf:"bytes,1,rep,name=vaults,proto3" json:"vaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserVaultsResponse) Reset() {
	*x = GetUserVaultsResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVaultsResponse) ProtoMessage() {}

func (x *GetUserVaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVaultsResponse.ProtoReflect.Descriptor instead.
func (*GetUserVaultsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserVaultsResponse) GetVaults() []*VaultItem {
	if x != nil {
		return x.Vaults
	}
	return nil
}

// Message represents request to soft delete secret from vault
type DeactivateVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      int32                  `protobuf:"varint,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateVaultRequest) Reset() {
	*x = DeactivateVaultRequest{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateVaultRequest) ProtoMessage() {}

func (x *DeactivateVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateVaultRequest.ProtoReflect.Descriptor instead.
func (*DeactivateVaultRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateVaultRequest) GetSecretId() int32 {
	if x != nil {
		return x.SecretId
	}
	return 0
}

// Message represents response to soft delete secret from vault
type DeactivateVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateVaultResponse) Reset() {
	*x = DeactivateVaultResponse{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateVaultResponse) ProtoMessage() {}

func (x *DeactivateVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateVaultResponse.ProtoReflect.Descriptor instead.
func (*DeactivateVaultResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateVaultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Message represents request to send streamed file data
type UploadFileRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	FileName string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_ChunkData
	//	*UploadFileRequest_MetaData
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *UploadFileRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

func (x *UploadFileRequest) GetMetaData() *structpb.Struct {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_MetaData); ok {
			return x.MetaData
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

type UploadFileRequest_MetaData struct {
	MetaData *structpb.Struct `protobuf:"bytes,3,opt,name=meta_data,json=metaData,proto3,oneof"`
}

func (*UploadFileRequest_ChunkData) isUploadFileRequest_Data() {}

func (*UploadFileRequest_MetaData) isUploadFileRequest_Data() {}

// Message represents streamed response to retrieve all vaults saved by user
type VaultItemChunk struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Item               *VaultItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	EncryptedDataChunk []byte                 `protobuf:"bytes,2,opt,name=encrypted_data_chunk,json=encryptedDataChunk,proto3" json:"encrypted_data_chunk,omitempty"`
	ChunkIndex         int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks        int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	IsFirstChunk       bool                   `protobuf:"varint,5,opt,name=is_first_chunk,json=isFirstChunk,proto3" json:"is_first_chunk,omitempty"`
	IsLastChunk        bool                   `protobuf:"varint,6,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VaultItemChunk) Reset() {
	*x = VaultItemChunk{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItemChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItemChunk) ProtoMessage() {}

func (x *VaultItemChunk) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultItemChunk.ProtoReflect.Descriptor instead.
func (*VaultItemChunk) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *VaultItemChunk) GetItem() *VaultItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *VaultItemChunk) GetEncryptedDataChunk() []byte {
	if x != nil {
		return x.EncryptedDataChunk
	}
	return nil
}

func (x *VaultItemChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *VaultItemChunk) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *VaultItemChunk) GetIsFirstChunk() bool {
	if x != nil {
		return x.IsFirstChunk
	}
	return false
}

func (x *VaultItemChunk) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

type StreamMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalItems       int32                  `protobuf:"varint,1,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	CurrentItemIndex int32                  `protobuf:"varint,2,opt,name=current_item_index,json=currentItemIndex,proto3" json:"current_item_index,omitempty"`
	IsFirstItem      bool                   `protobuf:"varint,3,opt,name=is_first_item,json=isFirstItem,proto3" json:"is_first_item,omitempty"`
	IsLastItem       bool                   `protobuf:"varint,4,opt,name=is_last_item,json=isLastItem,proto3" json:"is_last_item,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamMetadata) Reset() {
	*x = StreamMetadata{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetadata) ProtoMessage() {}

func (x *StreamMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetadata.ProtoReflect.Descriptor instead.
func (*StreamMetadata) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *StreamMetadata) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *StreamMetadata) GetCurrentItemIndex() int32 {
	if x != nil {
		return x.CurrentItemIndex
	}
	return 0
}

func (x *StreamMetadata) GetIsFirstItem() bool {
	if x != nil {
		return x.IsFirstItem
	}
	return false
}

func (x *StreamMetadata) GetIsLastItem() bool {
	if x != nil {
		return x.IsLastItem
	}
	return false
}

type StreamVaultsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamVaultsResponse_ItemChunk
	//	*StreamVaultsResponse_Metadata
	Payload       isStreamVaultsResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamVaultsResponse) Reset() {
	*x = StreamVaultsResponse{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamVaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamVaultsResponse) ProtoMessage() {}

func (x *StreamVaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamVaultsResponse.ProtoReflect.Descriptor instead.
func (*StreamVaultsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *StreamVaultsResponse) GetPayload() isStreamVaultsResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamVaultsResponse) GetItemChunk() *VaultItemChunk {
	if x != nil {
		if x, ok := x.Payload.(*StreamVaultsResponse_ItemChunk); ok {
			return x.ItemChunk
		}
	}
	return nil
}

func (x *StreamVaultsResponse) GetMetadata() *StreamMetadata {
	if x != nil {
		if x, ok := x.Payload.(*StreamVaultsResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

type isStreamVaultsResponse_Payload interface {
	isStreamVaultsResponse_Payload()
}

type StreamVaultsResponse_ItemChunk struct {
	ItemChunk *VaultItemChunk `protobuf:"bytes,1,opt,name=item_chunk,json=itemChunk,proto3,oneof"`
}

type StreamVaultsResponse_Metadata struct {
	Metadata *StreamMetadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof"`
}

func (*StreamVaultsResponse_ItemChunk) isStreamVaultsResponse_Payload() {}

func (*StreamVaultsResponse_Metadata) isStreamVaultsResponse_Payload() {}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Login           string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\x06server\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"G\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"l\n" +
	"\x14RegisterUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"C\n" +
	"\x11LoginUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\x10SaveVaultRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12#\n" +
	"\recrypted_data\x18\x03 \x01(\fR\fecryptedData\x124\n" +
	"\tmeta_data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetaData\"-\n" +
	"\x11SaveVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x02\n" +
	"\tVaultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x04 \x01(\tR\bdataType\x12%\n" +
	"\x0eencrypted_data\x18\x05 \x01(\fR\rencryptedData\x124\n" +
	"\tmeta_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetaData\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06active\x18\t \x01(\bR\x06active\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\"B\n" +
	"\x15GetUserVaultsResponse\x12)\n" +
	"\x06vaults\x18\x01 \x03(\v2\x11.server.VaultItemR\x06vaults\"5\n" +
	"\x16DeactivateVaultRequest\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\x05R\bsecretId\"3\n" +
	"\x17DeactivateVaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x91\x01\n" +
	"\x11UploadFileRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkData\x126\n" +
	"\tmeta_data\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\bmetaDataB\x06\n" +
	"\x04data\"\xf7\x01\n" +
	"\x0eVaultItemChunk\x12%\n" +
	"\x04item\x18\x01 \x01(\v2\x11.server.VaultItemR\x04item\x120\n" +
	"\x14encrypted_data_chunk\x18\x02 \x01(\fR\x12encryptedDataChunk\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12$\n" +
	"\x0eis_first_chunk\x18\x05 \x01(\bR\fisFirstChunk\x12\"\n" +
	"\ris_last_chunk\x18\x06 \x01(\bR\visLastChunk\"\xa5\x01\n" +
	"\x0eStreamMetadata\x12\x1f\n" +
	"\vtotal_items\x18\x01 \x01(\x05R\n" +
	"totalItems\x12,\n" +
	"\x12current_item_index\x18\x02 \x01(\x05R\x10currentItemIndex\x12\"\n" +
	"\ris_first_item\x18\x03 \x01(\bR\visFirstItem\x12 \n" +
	"\fis_last_item\x18\x04 \x01(\bR\n" +
	"isLastItem\"\x90\x01\n" +
	"\x14StreamVaultsResponse\x127\n" +
	"\n" +
	"item_chunk\x18\x01 \x01(\v2\x16.server.VaultItemChunkH\x00R\titemChunk\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x16.server.StreamMetadataH\x00R\bmetadataB\t\n" +
	"\apayload\"{\n" +
	"\x15ChangePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x86\x05\n" +
	"\n" +
	"GophKeeper\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fRegisterUser\x12\x1b.server.RegisterUserRequest\x1a\x1c.server.RegisterUserResponse\x12@\n" +
	"\tLoginUser\x12\x18.server.LoginUserRequest\x1a\x19.server.LoginUserResponse\x12@\n" +
	"\tSaveVault\x12\x18.server.SaveVaultRequest\x1a\x19.server.SaveVaultResponse\x12B\n" +
	"\tGetVaults\x12\x16.google.protobuf.Empty\x1a\x1d.server.GetUserVaultsResponse\x12R\n" +
	"\x0fDeactivateVault\x12\x1e.server.DeactivateVaultRequest\x1a\x1f.server.DeactivateVaultResponse\x12<\n" +
	"\n" +
	"UploadFile\x12\x19.server.UploadFileRequest\x1a\x11.server.VaultItem(\x01\x12J\n" +
	"\x10GetSteamedVaults\x12\x16.google.protobuf.Empty\x1a\x1c.server.StreamVaultsResponse0\x01\x12O\n" +
	"\x0eChangePassword\x12\x1d.server.ChangePasswordRequest\x1a\x1e.server.ChangePasswordResponseB\x17Z\x15internal/server/protob\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_server_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),     // 0: server.RegisterUserRequest
	(*RegisterUserResponse)(nil),    // 1: server.RegisterUserResponse
	(*LoginUserRequest)(nil),        // 2: server.LoginUserRequest
	(*LoginUserResponse)(nil),       // 3: server.LoginUserResponse
	(*SaveVaultRequest)(nil),        // 4: server.SaveVaultRequest
	(*SaveVaultResponse)(nil),       // 5: server.SaveVaultResponse
	(*VaultItem)(nil),               // 6: server.VaultItem
	(*GetUserVaultsResponse)(nil),   // 7: server.GetUserVaultsResponse
	(*DeactivateVaultRequest)(nil),  // 8: server.DeactivateVaultRequest
	(*DeactivateVaultResponse)(nil), // 9: server.DeactivateVaultResponse
	(*UploadFileRequest)(nil),       // 10: server.UploadFileRequest
	(*VaultItemChunk)(nil),          // 11: server.VaultItemChunk
	(*StreamMetadata)(nil),          // 12: server.StreamMetadata
	(*StreamVaultsResponse)(nil),    // 13: server.StreamVaultsResponse
	(*ChangePasswordRequest)(nil),   // 14: server.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),  // 15: server.ChangePasswordResponse
	(*structpb.Struct)(nil),         // 16: google.protobuf.Struct
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
}
var file_server_proto_depIdxs = []int32{
	16, // 0: server.SaveVaultRequest.meta_data:type_name -> google.protobuf.Struct
	16, // 1: server.VaultItem.meta_data:type_name -> google.protobuf.Struct
	6,  // 2: server.GetUserVaultsResponse.vaults:type_name -> server.VaultItem
	16, // 3: server.UploadFileRequest.meta_data:type_name -> google.protobuf.Struct
	6,  // 4: server.VaultItemChunk.item:type_name -> server.VaultItem
	11, // 5: server.StreamVaultsResponse.item_chunk:type_name -> server.VaultItemChunk
	12, // 6: server.StreamVaultsResponse.metadata:type_name -> server.StreamMetadata
	17, // 7: server.GophKeeper.Ping:input_type -> google.protobuf.Empty
	0,  // 8: server.GophKeeper.RegisterUser:input_type -> server.RegisterUserRequest
	2,  // 9: server.GophKeeper.LoginUser:input_type -> server.LoginUserRequest
	4,  // 10: server.GophKeeper.SaveVault:input_type -> server.SaveVaultRequest
	17, // 11: server.GophKeeper.GetVaults:input_type -> google.protobuf.Empty
	8,  // 12: server.GophKeeper.DeactivateVault:input_type -> server.DeactivateVaultRequest
	10, // 13: server.GophKeeper.UploadFile:input_type -> server.UploadFileRequest
	17, // 14: server.GophKeeper.GetSteamedVaults:input_type -> google.protobuf.Empty
	14, // 15: server.GophKeeper.ChangePassword:input_type -> server.ChangePasswordRequest
	17, // 16: server.GophKeeper.Ping:output_type -> google.protobuf.Empty
	1,  // 17: server.GophKeeper.RegisterUser:output_type -> server.RegisterUserResponse
	3,  // 18: server.GophKeeper.LoginUser:output_type -> server.LoginUserResponse
	5,  // 19: server.GophKeeper.SaveVault:output_type -> server.SaveVaultResponse
	7,  // 20: server.GophKeeper.GetVaults:output_type -> server.GetUserVaultsResponse
	9,  // 21: server.GophKeeper.DeactivateVault:output_type -> server.DeactivateVaultResponse
	6,  // 22: server.GophKeeper.UploadFile:output_type -> server.VaultItem
	13, // 23: server.GophKeeper.GetSteamedVaults:output_type -> server.StreamVaultsResponse
	15, // 24: server.GophKeeper.ChangePassword:output_type -> server.ChangePasswordResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_server_proto_msgTypes[10].OneofWrappers = []any{
		(*UploadFileRequest_ChunkData)(nil),
		(*UploadFileRequest_MetaData)(nil),
	}
	file_server_proto_msgTypes[13].OneofWrappers = []any{
		(*StreamVaultsResponse_ItemChunk)(nil),
		(*StreamVaultsResponse_Metadata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
