syntax = "proto3";

package server;

option go_package = "internal/server/proto";

import "google/protobuf/struct.proto";


service GophKeeper {
  // Service health
  rpc Ping(PingRequest) returns (PingResponse);
  // Register new user
  rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
  // Login user
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse);
  // Change user password
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
  // SaveVault saves new record to vault
  rpc SaveVault(SaveVaultRequest) returns (SaveVaultResponse);
  // Login user
  rpc DeactivateVault(DeactivateVaultRequest) returns (DeactivateVaultResponse);
  // UploadFile is used to send binary data as stream of chunks
  rpc UploadFile (stream UploadFileRequest) returns (VaultItem);
  // Retrieve all vaults saved by user using streamed response
  rpc GetSteamedVaults(StreamVaultsRequest) returns (stream StreamVaultsResponse);
  // UpdateVault is used to update specific vault record with new data
  rpc UpdateVault(UpdateVaultRequest) returns (UpdateVaultResponse);
}

// Messages for service health
message PingRequest {}

message PingResponse {}


// Messages for user registration
message RegisterUserRequest {
    string login = 1;
    string password = 2;
}

message RegisterUserResponse {
    uint64 id = 1;
    string login = 2;
    string token = 3;
    bool success = 4;
}

// Messages for user login
message LoginUserRequest {
    string login = 1;
    string password = 2;
}

message LoginUserResponse {
    string token = 1;
    bool success = 2;
}

// Messages for changing password
message ChangePasswordRequest {
    string current_password = 1;
    string new_password = 2;
    string login = 3;
}

message ChangePasswordResponse {
    bool success = 1;
}

// Message for saving new vault data
message SaveVaultRequest {
    string name = 1;
    string data_type = 2;
    bytes ecrypted_data = 3;
    google.protobuf.Struct meta_data = 4;
}

message SaveVaultResponse {
    bool success = 1;
}

// Message for soft deletion of user's vault record
message DeactivateVaultRequest {
    int32 secret_id = 1;
}

message DeactivateVaultResponse {
    bool success = 1;
}

// Messages for fetching user's vaults using streams
message VaultItem {
    int32 id = 1;
    int32 user_id = 2;
    string name = 3;
    string data_type = 4;
    bytes encrypted_data = 5;
    google.protobuf.Struct meta_data = 6;
    string created_at = 7;
    string updated_at = 8;
    bool active = 9;
    int32 version = 10;
}

message VaultItemChunk {
    VaultItem item = 1;
    bytes encrypted_data_chunk = 2;
    int32 chunk_index = 3;
    int32 total_chunks = 4;
    bool is_first_chunk = 5;
    bool is_last_chunk = 6;
}

message StreamMetadata {
    int32 total_items = 1;
    int32 current_item_index = 2;
    bool is_first_item = 3;
    bool is_last_item = 4;
}


message StreamVaultsRequest {}

message StreamVaultsResponse {
    oneof payload {
        VaultItemChunk item_chunk = 1;
        StreamMetadata metadata = 2;
    }
}

// Messages for uploading file data into the vault using chunks
message UploadFileRequest {
    string file_name = 1;
    oneof data {
        bytes chunk_data = 2;
        google.protobuf.Struct meta_data = 3;
  };
}


// Message for updating vault record
message UpdateVaultRequest {
    int32 id = 1;
    string name = 2;
    bytes encrypted_data = 3;
    google.protobuf.Struct meta_data = 4;
}

message UpdateVaultResponse {
    bool success = 1;
    string message = 2;
}