// Code generated by MockGen. DO NOT EDIT.
// Source: vault.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/dangerousmonk/gophkeeper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockVaultHandler is a mock of VaultHandler interface.
type MockVaultHandler struct {
	ctrl     *gomock.Controller
	recorder *MockVaultHandlerMockRecorder
}

// MockVaultHandlerMockRecorder is the mock recorder for MockVaultHandler.
type MockVaultHandlerMockRecorder struct {
	mock *MockVaultHandler
}

// NewMockVaultHandler creates a new mock instance.
func NewMockVaultHandler(ctrl *gomock.Controller) *MockVaultHandler {
	mock := &MockVaultHandler{ctrl: ctrl}
	mock.recorder = &MockVaultHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultHandler) EXPECT() *MockVaultHandlerMockRecorder {
	return m.recorder
}

// Deactivate mocks base method.
func (m *MockVaultHandler) Deactivate(ctx context.Context, userID, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockVaultHandlerMockRecorder) Deactivate(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockVaultHandler)(nil).Deactivate), ctx, userID, id)
}

// GetByUser mocks base method.
func (m *MockVaultHandler) GetByUser(ctx context.Context, userID int) ([]models.Vault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Vault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUser indicates an expected call of GetByUser.
func (mr *MockVaultHandlerMockRecorder) GetByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUser", reflect.TypeOf((*MockVaultHandler)(nil).GetByUser), ctx, userID)
}

// Save mocks base method.
func (m *MockVaultHandler) Save(ctx context.Context, req *models.Vault) (*models.Vault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, req)
	ret0, _ := ret[0].(*models.Vault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockVaultHandlerMockRecorder) Save(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockVaultHandler)(nil).Save), ctx, req)
}

// Update mocks base method.
func (m *MockVaultHandler) Update(ctx context.Context, id, userID int, name string, encryptedData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, name, encryptedData)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVaultHandlerMockRecorder) Update(ctx, id, userID, name, encryptedData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVaultHandler)(nil).Update), ctx, id, userID, name, encryptedData)
}
